title: t1b4n3
description: Offensive Security Researcher
url: "https://t1b4n3.github.io"

markdown: kramdown
highlighter: rouge


permalink: /:categories/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

plugins:
  - jekyll-feed